// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class CheckResult {
    "local": string;
    "remote": string;
    "assetName": string;
    "assetURL": string;
    "assetSize": number;
    "newer": boolean;
    "htmlUrl": string;
    "wouldWrite"?: string[];
    "restart": boolean;
    "appId": string;

    /** Creates a new CheckResult instance. */
    constructor($$source: Partial<CheckResult> = {}) {
        if (!("local" in $$source)) {
            this["local"] = "";
        }
        if (!("remote" in $$source)) {
            this["remote"] = "";
        }
        if (!("assetName" in $$source)) {
            this["assetName"] = "";
        }
        if (!("assetURL" in $$source)) {
            this["assetURL"] = "";
        }
        if (!("assetSize" in $$source)) {
            this["assetSize"] = 0;
        }
        if (!("newer" in $$source)) {
            this["newer"] = false;
        }
        if (!("htmlUrl" in $$source)) {
            this["htmlUrl"] = "";
        }
        if (!("restart" in $$source)) {
            this["restart"] = false;
        }
        if (!("appId" in $$source)) {
            this["appId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CheckResult {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wouldWrite" in $$parsedSource) {
            $$parsedSource["wouldWrite"] = $$createField7_0($$parsedSource["wouldWrite"]);
        }
        return new CheckResult($$parsedSource as Partial<CheckResult>);
    }
}

/**
 * UpcomingItem is the next fire of one enabled app schedule.
 */
export class UpcomingItem {
    "time": string;
    "appId": string;
    "appName": string;
    "action": string;

    /** Creates a new UpcomingItem instance. */
    constructor($$source: Partial<UpcomingItem> = {}) {
        if (!("time" in $$source)) {
            this["time"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("appId" in $$source)) {
            this["appId"] = "";
        }
        if (!("appName" in $$source)) {
            this["appName"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpcomingItem instance from a string or object.
     */
    static createFrom($$source: any = {}): UpcomingItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpcomingItem($$parsedSource as Partial<UpcomingItem>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
