// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as githubsrc$0 from "../githubsrc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "../history/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as host$0 from "../host/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as preset$0 from "../preset/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyPreset(id: string): $CancellablePromise<config$0.App> {
    return $Call.ByID(116153453, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function BrowseExe(): $CancellablePromise<string> {
    return $Call.ByID(162008196);
}

export function BrowseShortcut(): $CancellablePromise<string> {
    return $Call.ByID(3229052430);
}

export function CheckNow(id: string): $CancellablePromise<$models.CheckResult | null> {
    return $Call.ByID(3199887590, id).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ConsumePendingOpen returns (and clears) an app id from a protocol launch
 * (toast click or second instance). The frontend calls this after it is mounted
 * because the first-launch event is emitted before WebView2 is ready.
 */
export function ConsumePendingOpen(): $CancellablePromise<string> {
    return $Call.ByID(2241266407);
}

export function DeleteApp(id: string): $CancellablePromise<void> {
    return $Call.ByID(1306349344, id);
}

export function DisableEncryption(password: string): $CancellablePromise<void> {
    return $Call.ByID(3546993123, password);
}

export function EnableEncryption(password: string): $CancellablePromise<void> {
    return $Call.ByID(1361849884, password);
}

export function Encrypted(): $CancellablePromise<boolean> {
    return $Call.ByID(135570830);
}

export function GetConfig(): $CancellablePromise<config$0.Settings> {
    return $Call.ByID(923510764).then(($result: any) => {
        return $$createType3($result);
    });
}

export function History(limit: number): $CancellablePromise<history$0.Event[]> {
    return $Call.ByID(2692803822, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

export function HostArch(): $CancellablePromise<string> {
    return $Call.ByID(1832405432);
}

export function LocalVersion(app: config$0.App): $CancellablePromise<string> {
    return $Call.ByID(3609577631, app);
}

export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(215077873);
}

export function NeedsUnlock(): $CancellablePromise<boolean> {
    return $Call.ByID(585638023);
}

export function ParseShortcut(path: string): $CancellablePromise<host$0.Shortcut> {
    return $Call.ByID(1655394423, path).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Presets(): $CancellablePromise<preset$0.Info[]> {
    return $Call.ByID(1384801202).then(($result: any) => {
        return $$createType8($result);
    });
}

export function PreviewGitHub(ownerRepo: string): $CancellablePromise<githubsrc$0.Release | null> {
    return $Call.ByID(3375784449, ownerRepo).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ProtocolURL(id: string): $CancellablePromise<string> {
    return $Call.ByID(1791471375, id);
}

export function SaveApp(app: config$0.App): $CancellablePromise<config$0.App> {
    return $Call.ByID(974972566, app).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveConfig($in: config$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(387211169, $in);
}

export function ShowApp(id: string): $CancellablePromise<void> {
    return $Call.ByID(2395561486, id);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(2027498995);
}

export function Unlock(password: string): $CancellablePromise<void> {
    return $Call.ByID(449477858, password);
}

export function Upcoming(): $CancellablePromise<$models.UpcomingItem[]> {
    return $Call.ByID(3613454320).then(($result: any) => {
        return $$createType12($result);
    });
}

export function UpgradeNow(id: string): $CancellablePromise<$models.CheckResult | null> {
    return $Call.ByID(31310198, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function WouldWrite(exePath: string, extra: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(834107566, exePath, extra).then(($result: any) => {
        return $$createType13($result);
    });
}

// Private type creation functions
const $$createType0 = config$0.App.createFrom;
const $$createType1 = $models.CheckResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = config$0.Settings.createFrom;
const $$createType4 = history$0.Event.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = host$0.Shortcut.createFrom;
const $$createType7 = preset$0.Info.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = githubsrc$0.Release.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.UpcomingItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($Create.Any);
