// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Event is one persisted history line.
 */
export class Event {
    "time": string;
    "appId": string;
    "appName": string;
    "action": string;
    "from"?: string;
    "to"?: string;
    "asset"?: string;
    "result"?: string;
    "error"?: string;

    /** Creates a new Event instance. */
    constructor($$source: Partial<Event> = {}) {
        if (!("time" in $$source)) {
            this["time"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("appId" in $$source)) {
            this["appId"] = "";
        }
        if (!("appName" in $$source)) {
            this["appName"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     */
    static createFrom($$source: any = {}): Event {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Event($$parsedSource as Partial<Event>);
    }
}
