// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Asset is a GitHub release asset we might download.
 */
export class Asset {
    "name": string;
    "browser_download_url": string;
    "size": number;

    /** Creates a new Asset instance. */
    constructor($$source: Partial<Asset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("browser_download_url" in $$source)) {
            this["browser_download_url"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Asset instance from a string or object.
     */
    static createFrom($$source: any = {}): Asset {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Asset($$parsedSource as Partial<Asset>);
    }
}

/**
 * Release is a GitHub tagged release plus the asset we would download.
 */
export class Release {
    "tag_name": string;
    "name": string;
    "html_url": string;
    "published_at": string;
    "assets": Asset[];
    "asset": Asset;

    /** Creates a new Release instance. */
    constructor($$source: Partial<Release> = {}) {
        if (!("tag_name" in $$source)) {
            this["tag_name"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("html_url" in $$source)) {
            this["html_url"] = "";
        }
        if (!("published_at" in $$source)) {
            this["published_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("assets" in $$source)) {
            this["assets"] = [];
        }
        if (!("asset" in $$source)) {
            this["asset"] = (new Asset());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Release instance from a string or object.
     */
    static createFrom($$source: any = {}): Release {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField4_0($$parsedSource["assets"]);
        }
        if ("asset" in $$parsedSource) {
            $$parsedSource["asset"] = $$createField5_0($$parsedSource["asset"]);
        }
        return new Release($$parsedSource as Partial<Release>);
    }
}

// Private type creation functions
const $$createType0 = Asset.createFrom;
const $$createType1 = $Create.Array($$createType0);
