// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Shortcut is a parsed .lnk (best-effort).
 */
export class Shortcut {
    "target": string;
    "arguments": string;
    "workingDir": string;
    "icon": string;
    "description": string;

    /** Creates a new Shortcut instance. */
    constructor($$source: Partial<Shortcut> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("arguments" in $$source)) {
            this["arguments"] = "";
        }
        if (!("workingDir" in $$source)) {
            this["workingDir"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Shortcut instance from a string or object.
     */
    static createFrom($$source: any = {}): Shortcut {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Shortcut($$parsedSource as Partial<Shortcut>);
    }
}
