#!/usr/bin/env bash
# Write Windows VERSIONINFO inputs for `wails3 generate syso` and NSIS.
# File version is Major.Minor.Patch.REVISION (same fourth number unpackerr
# stamps). Product version is the release string (tag without v).
# Do not use a previous tag's x.y.z: VERSION comes from this build's tag.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "${ROOT}"

product_version() {
  if [ -n "${VERSION:-}" ]; then
    echo "${VERSION#v}"
    return
  fi
  if [ -n "${GITHUB_REF_NAME:-}" ] && [[ "${GITHUB_REF_NAME}" == v* ]]; then
    echo "${GITHUB_REF_NAME#v}"
    return
  fi
  local tag
  tag="$(git describe --tags --exact-match HEAD 2>/dev/null || git describe --tags --abbrev=0 2>/dev/null || true)"
  tag="${tag#v}"
  echo "${tag:-0.0.0}"
}

revision() {
  if [ -n "${REVISION:-}" ]; then
    echo "${REVISION}"
    return
  fi
  git rev-list --count --all
}

VERSION="$(product_version)"
REVISION="$(revision)"
if ! [[ "${REVISION}" =~ ^[0-9]+$ ]]; then
  echo "REVISION must be an integer, got ${REVISION}" >&2
  exit 1
fi

XYZ="${VERSION%%-*}"
XYZ="${XYZ%%+*}"
IFS=. read -r VER_MAJOR VER_MINOR VER_PATCH _ <<EOF
${XYZ}
EOF
VER_MAJOR="${VER_MAJOR:-0}"
VER_MINOR="${VER_MINOR:-0}"
VER_PATCH="${VER_PATCH:-0}"
FILE_VERSION="${VER_MAJOR}.${VER_MINOR}.${VER_PATCH}.${REVISION}"

mkdir -p "${ROOT}/build/windows/nsis"

cat >"${ROOT}/build/windows/info.stamped.json" <<EOF
{
	"fixed": {
		"file_version": "${FILE_VERSION}",
		"product_version": "${FILE_VERSION}"
	},
	"info": {
		"0000": {
			"ProductVersion": "${VERSION}",
			"FileVersion": "${FILE_VERSION}",
			"CompanyName": "TwitchCaptain",
			"FileDescription": "Keep Windows apps current from GitHub releases",
			"LegalCopyright": "Copyright TwitchCaptain",
			"ProductName": "Captain Updater",
			"Comments": "Captain Updater",
			"InternalName": "captain-updater",
			"OriginalFilename": "captain-updater.exe"
		}
	}
}
EOF

awk -v ver="${FILE_VERSION}" '
  /assemblyIdentity type="win32" name="com.twitchcaptain.updater"/ {
    sub(/version="[^"]*"/, "version=\"" ver "\"")
  }
  { print }
' "${ROOT}/build/windows/wails.exe.manifest" >"${ROOT}/build/windows/wails.exe.manifest.stamped"

cat >"${ROOT}/build/windows/nsis/version.generated.nsh" <<EOF
; Generated by init/windows/stamp-version.sh — do not edit
!define INFO_PRODUCTVERSION "${VERSION}"
!define INFO_FILEVERSION "${FILE_VERSION}"
EOF

echo "Stamped Windows FileVersion ${FILE_VERSION} ProductVersion ${VERSION}" >&2
