// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schedule$0 from "../schedule/models.js";

/**
 * App is one GitHub product to keep current.
 */
export class App {
    "id": string;
    "name": string;
    "enabled": boolean;
    "source": string;
    "ownerRepo": string;
    "exePath": string;
    "shortcutPath"?: string;
    "extraFiles"?: string[];
    "versionHttp"?: string;
    "versionJson"?: string;
    "versionHttpHeader"?: string;
    "versionHttpSecret"?: string;
    "lastVersion"?: string;
    "schedules": schedule$0.Slot[];

    /** Creates a new App instance. */
    constructor($$source: Partial<App> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("ownerRepo" in $$source)) {
            this["ownerRepo"] = "";
        }
        if (!("exePath" in $$source)) {
            this["exePath"] = "";
        }
        if (!("schedules" in $$source)) {
            this["schedules"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new App instance from a string or object.
     */
    static createFrom($$source: any = {}): App {
        const $$createField7_0 = $$createType0;
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extraFiles" in $$parsedSource) {
            $$parsedSource["extraFiles"] = $$createField7_0($$parsedSource["extraFiles"]);
        }
        if ("schedules" in $$parsedSource) {
            $$parsedSource["schedules"] = $$createField13_0($$parsedSource["schedules"]);
        }
        return new App($$parsedSource as Partial<App>);
    }
}

/**
 * Settings is the on-disk config (minus encryption wrapper).
 */
export class Settings {
    "githubToken"?: string;
    "startWithWindows": boolean;
    "apps": App[];

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("startWithWindows" in $$source)) {
            this["startWithWindows"] = false;
        }
        if (!("apps" in $$source)) {
            this["apps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apps" in $$parsedSource) {
            $$parsedSource["apps"] = $$createField2_0($$parsedSource["apps"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = schedule$0.Slot.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = App.createFrom;
const $$createType4 = $Create.Array($$createType3);
