// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Info is a built-in template the user still has to point at a local exe.
 */
export class Info {
    "id": string;
    "name": string;
    "ownerRepo": string;
    "primaryExe": string;
    "extraFiles": string[];
    "versionHttp"?: string;
    "versionJson"?: string;
    "notes": string;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("ownerRepo" in $$source)) {
            this["ownerRepo"] = "";
        }
        if (!("primaryExe" in $$source)) {
            this["primaryExe"] = "";
        }
        if (!("extraFiles" in $$source)) {
            this["extraFiles"] = [];
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extraFiles" in $$parsedSource) {
            $$parsedSource["extraFiles"] = $$createField4_0($$parsedSource["extraFiles"]);
        }
        return new Info($$parsedSource as Partial<Info>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
