// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Slot is one weekly fire time. Days uses time.Weekday (Sunday=0).
 */
export class Slot {
    "days": time$0.Weekday[];

    /**
     * HH:MM 24h local
     */
    "time": string;
    "action": string;

    /** Creates a new Slot instance. */
    constructor($$source: Partial<Slot> = {}) {
        if (!("days" in $$source)) {
            this["days"] = [];
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Slot instance from a string or object.
     */
    static createFrom($$source: any = {}): Slot {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("days" in $$parsedSource) {
            $$parsedSource["days"] = $$createField0_0($$parsedSource["days"]);
        }
        return new Slot($$parsedSource as Partial<Slot>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
